### ISSUE TITLE
(Feature Request) Add MacOS support 

### ISSUE THREAD

**Issue by inzar98** [Arctium/WoW-Launcher#15]
I love to play vanilla and future wotlk servers. There is no way to play on m1 chips now.

https://github.com/WowLegacyCore/HermesProxy/issues/78#issuecomment-1200156900

with arctium apple slicon devices can play wow natively

**Comment by Fabi** [comment]
> I love to play vanilla and future wotlk servers. There is no way to play on m1 chips now.
> 
> [WowLegacyCore/HermesProxy#78 (comment)](https://github.com/WowLegacyCore/HermesProxy/issues/78#issuecomment-1200156900)
> 
> with arctium apple slicon devices can play wow natively

With the static auth seed being a thing now I might be able to push my macOS launcher very soon I think.

It's basically finished but it was for x86 macOS only. I'm getting my new Mac book next week (still waiting...) probably so I'll most likely finish those

**Comment by x92mko** [comment]
that would be outstanding! :)

**Comment by inzar98** [comment]
Im so glad to hear that !!! Thank you for all

**Comment by BigKananga** [comment]
> With the static auth seed

Where can I download the static auth seed Windows build?

**Comment by ReynoldsCahoon** [comment]
Any updates on this @Fabi ?

**Comment by Fabi** [comment]
> Any updates on this @Fabi ?

I currently focus on macOS ARM support but there are a few new unexpected issues

**Comment by BigKananga** [comment]
@Fabi 
Where can I download the static auth seed Windows build?

**Comment by oboje** [comment]
how can we help ??

came here after the hermes... i don't want to miss epic overlook start :D

**Comment by oboje** [comment]
p.s guys, 
have you managed to run hermes on macOS, the only way I see is to run it in virtual machine.

**Comment by inzar98** [comment]
> p.s guys,
> have you managed to run hermes on macOS, the only way I see is to run it in virtual machine.

Thats not mean running on macos btw…

**Comment by Bemyth** [comment]
> > I love to play vanilla and future wotlk servers. There is no way to play on m1 chips now.
> > [WowLegacyCore/HermesProxy#78 (comment)](https://github.com/WowLegacyCore/HermesProxy/issues/78#issuecomment-1200156900)
> > with arctium apple slicon devices can play wow natively
> 
> With the static auth seed being a thing now I might be able to push my macOS launcher very soon I think.
> 
> It's basically finished but it was for x86 macOS only. I'm getting my new Mac book next week (still waiting...) probably so I'll most likely finish those

I need it for my old mac (10.15), can you provide a mac x86 version if possible? thank you very much!

**Comment by strangeliu** [comment]
Any updates on apple silicon support?

**Comment by zer0xtgs** [comment]
Any updates for the mac os version? especially x86 version

**Comment by Fabi** [comment]
> Any updates for the mac os version? especially x86 version

It is VERY unlikely that x86 support for macOS will ever gets added. ARM support is kind of done. If there is not a big difference I'll do x86 too.

**Comment by WebberLai** [comment]
X86 release will be great !!!
I try to open your project in Mac Visual studio , it shows an error "need .net 7"
so I download and install it
open again , it shows this version not support 
WTF Miscro$oft

**Comment by Brianelvio** [comment]
> It is VERY unlikely that x86 support for macOS will ever gets added. ARM support is kind of done. If there is not a big difference I'll do x86 too.

Appreciate the awesome work that you do! Do you have any indication when the ARM version is released / open for testing? :)

**Comment by WayneSunJazz** [comment]
Wating for m1 mac version too. you are awsome!

**Comment by ZaDarkSide** [comment]
![giphy](https://user-images.githubusercontent.com/291278/234941143-b1a16172-a189-4ed5-86aa-d0f9068b4022.gif)

**Comment by donluca** [comment]
One more vote for Mac Apple Silicon support!
This could be huge as it would allow us to still play Vanilla WoW on modern M1/M2 Macs.

**Comment by amenht** [comment]
Wating for X86  Mac version too, @Fabi you are awsome!

**Comment by Hyde7548** [comment]
> > Any updates for the mac os version? especially x86 version
> 
> It is VERY unlikely that x86 support for macOS will ever gets added. ARM support is kind of done. If there is not a big difference I'll do x86 too.

Hello Fabi, any update on the ARM support? Keep up the good work!

**Comment by ZaDarkSide** [comment]
![When?](https://github.com/Arctium/WoW-Launcher/assets/291278/e66f9764-afde-4245-8d66-4466559a4b27)

**Comment by Hyde7548** [comment]
If anyone has tried to launch the Windows version via the new mac games toolkit (or its GUI Whisky), just know that it doesn't work. The arctium launcher terminal window opens correctly bust jut loops in "Starting WoW client..."

**Comment by inzar98** [comment]
> If anyone has tried to launch the Windows version via the new mac games toolkit (or its GUI Whisky), just know that it doesn't work. The arctium launcher terminal window opens correctly bust jut loops in "Starting WoW client..."

Well we need apple silicon native.

**Comment by Hyde7548** [comment]
> > If anyone has tried to launch the Windows version via the new mac games toolkit (or its GUI Whisky), just know that it doesn't work. The arctium launcher terminal window opens correctly bust jut loops in "Starting WoW client..."
> 
> Well we need apple silicon native.

Indeed but I thought it was worth mentionning since relevant to the topic. Also, even the ARM-Mac OS version of WoW classic currently doesn't work on Mac OS Sonoma beta.

**Comment by inzar98** [comment]
> > > If anyone has tried to launch the Windows version via the new mac games toolkit (or its GUI Whisky), just know that it doesn't work. The arctium launcher terminal window opens correctly bust jut loops in "Starting WoW client..."
> > 
> > 
> > Well we need apple silicon native.
> 
> Indeed but I thought it was worth mentionning since relevant to the topic. Also, even the ARM-Mac OS version of WoW classic currently doesn't work on Mac OS Sonoma beta.

(OOT) oh really? Heavnt tried sonoma beta yet. Thats shame. But still classic era live blizz will update game

**Comment by x92mko** [comment]
Any native news?

**Comment by jactyao** [comment]
I hope for an early update for the Mac client. Thank you, thank you.

**Comment by kaine1973** [comment]
Any hope?

**Comment by mserajnik** [comment]
For anyone still looking for a solution __for Vanilla only__, https://github.com/0blu/WinterspringLauncher supports Apple Silicon on macOS and lets you use the 1.14 client with Vanilla servers.
I haven't done extensive testing yet (nor do I have prior experience with HermesProxy to know which potential issues to expect), but it seems to work just fine at first glance.

Note the usage instructions in the latest release, at the time of writing (https://github.com/0blu/WinterspringLauncher/releases/tag/1.5.0) you have to launch using `WinterspringLauncherTerminal`.

Once the client automatically starts for the first time after the download finishes, close it.

Then, simply change the value for `Realmlist` in `Users/<your-user>/WinterspringLauncher/winterspring-launcher-config.json` from `logon.everlook.org` to your desired server address. Do the same for `<add key="ServerAddress" value="logon.everlook.org" />` in `Users/<your-user>/WinterspringLauncher/hermes-proxy/HermesProxy.config`. This should allow you to connect to any VMaNGOS or CMaNGOS Classic server you want (some other parameters might need to be changed as well depending on the server configuration).

**Comment by kaine1973** [comment]
WinterspringLauncher doesn't seem to support latest build of wow dragonflight. It always try to download 1.14 client.
Also, I looked into his code, macOS doesn't support client patching: 
<img width="683" alt="截屏2023-09-01 13 04 25" src="https://github.com/Arctium/WoW-Launcher/assets/32561008/1ebcf651-fef3-4d70-976e-4f4683ad8016">

**Comment by mserajnik** [comment]
> WinterspringLauncher doesn't seem to support latest build of wow dragonflight. It always try to download 1.14 client.
> 
> Also, I looked into his code, macOS doesn't support client patching […]

You are right, WinterspringLauncher is only intended for using 1.14 clients with Vanilla servers (more specifically, Everlook, unless you adjust the configuration as I have illustrated).

I had based my previous comment on others asking for a solution for Vanilla here, I've now clarified that it's only for that.

**Comment by Fabi** [comment]
> WinterspringLauncher doesn't seem to support latest build of wow dragonflight. It always try to download 1.14 client. Also, I looked into his code, macOS doesn't support client patching: <img alt="截屏2023-09-01 13 04 25" width="683" src="https://user-images.githubusercontent.com/32561008/264928488-1ebcf651-fef3-4d70-976e-4f4683ad8016.png">

When I'm finally done you will have a launcher that also patches the wow binary and launches it then because that is easier. but the stuff I have is not fully ready yet and might be closed source for mac

**Comment by Fabi** [comment]
https://github.com/Arctium/WoW-Launcher/commit/3deaa3f50b95ae918ba49ca2a4d9a895247e67f7
