### ISSUE TITLE
Invalid Argument Staticseed 

### ISSUE THREAD

**Issue by Lmao-crim** [Arctium/WoW-Launcher#21]
After running  this In my wow directory     Arctium WoW Launcher.exe" -staticseed --version=ClassicEra    It runs then throws this  error at the end ---- Invalid Argument Staticseed

**Comment by Fabi** [comment]
--staticseed

**Comment by Lmao-crim** [comment]
![static](https://user-images.githubusercontent.com/112026034/203688447-caeccddc-ce60-4f08-a70f-416589909695.jpg)
Even When i add the Second - into the File name shortcut it still throws that error

**Comment by Fabi** [comment]
you use the shortcut or so wrong. it works on the provided releases.
