### ISSUE TITLE
can't lunch 1.14, but ask you to update game using battle.net!

### ISSUE THREAD

**Issue by WayneSunJazz** [Arctium/WoW-Launcher#24]
when i set all up .  it can't open the game . but pops up a window tell you that the game has update. and then show up battle net APP...
<img width="1868" alt="截屏2022-12-02 19 48 27" src="https://user-images.githubusercontent.com/119514624/205286480-a410db31-59bf-46d6-a27f-c3c36a1e887d.png">

Inviroment: m1 mac mini + PD 18.

**Comment by ratkosrb** [comment]
Did you forget to use the arctium launcher?

**Comment by WayneSunJazz** [comment]
> Did you forget to use the arctium launcher?

Of course I used sir.  Same method,  I try in my PC, open the game successfully！

So，I guess there is some problem these tow tools not compatible with PD18.

While I do can play 1.12 in PD18.

**Comment by Fabi** [comment]
> > Did you forget to use the arctium launcher?
> 
> Of course I used sir. Same method, I try in my PC, open the game successfully！
> 
> So，I guess there is some problem these tow tools not compatible with PD18.
> 
> While I do can play 1.12 in PD18.

PD does not change any behavior. It should be fixed when using the latest launcher now

**Comment by WayneSunJazz** [comment]
> > > Did you forget to use the arctium launcher?
> > 
> > 
> > Of course I used sir. Same method, I try in my PC, open the game successfully！
> > So，I guess there is some problem these tow tools not compatible with PD18.
> > While I do can play 1.12 in PD18.
> 
> PD does not change any behavior. It should be fixed when using the latest launcher now

Still a nagative. I try many times, same issue. 

I open the game by directly clicking  "World of Warcraft Launcher.exe"——show battle.net app
I open the game by clicking "Arctium WoW Launcher.exe" shortcut——show battle.net app

Turns out arctium launcher doesn't work. It doesn't bypass updating check system which it should.
Same method, works just fine on my PC.

**Comment by 0blu** [comment]
Don't install WoW on a network drive. Parallels uses a network drive to synchronize your files (`\\Mac`).

Place the game somewhere in `C:/`

**Comment by WayneSunJazz** [comment]
> 

OH, what you mentioned may be the reason of the issue. But I gave up playing WoW on everlook or other foreign server（I'm chinese，Ping too high). So I can't verify. Thank you anyway!

**Comment by WayneSunJazz** [comment]
> 

OH, what you mentioned may be the reason of the issue. But I gave up playing WoW on everlook or other foreign server（I'm chinese，Ping too high). So I can't verify. Thank you anyway!

**Comment by yuhuazhu** [comment]
> Don't install WoW on a network drive. Parallels uses a network drive to synchronize your files (`\\Mac`).
> 
> Place the game somewhere in `C:/`

You're right, Thanks!

Move the file to `C:` , game is play
