### ISSUE TITLE
Overwrite default support interface URL

### ISSUE THREAD

**Issue by 0blu** [Arctium/WoW-Launcher#25]
To make a ticket UI in modern clients possible the support URL must be overwritten.
Currently its default to the official one without a way to change it.

Challenges:
- Find function that passes the URL to the `BlizzardBrowser.exe`
- Modify the function to always pass the same domain _(for example `$PORTAL + "/support"`)_
- Find and modify the "trusted domains" function

**Comment by 0blu** [comment]
I think they are using `SendMessage` for IPC.

**Comment by Fabi** [comment]
> To make a ticket UI in modern clients possible the support URL must be overwritten. Currently its default to the official one without a way to change it.
> 
> Challenges:
> 
>     * Find function that passes the URL to the `BlizzardBrowser.exe`
> 
>     * Modify the function to always pass the same domain _(for example `$PORTAL + "/support"`)_
> 
>     * Find and modify the "trusted domains" function

The url itself is saved in GlobalStrings and can most likely be hotfixed (tested with a random db2 edit).

**Comment by 0blu** [comment]
Hotfixing did not work, I don't know if `VISITABLE_URL50` is even used for the browser.
