### ISSUE TITLE
Got BLZ51901016

### ISSUE THREAD

**Issue by FerdinandLBS** [Arctium/WoW-Launcher#29]
Hi, I fresh installed latest version(10.0.2(47213)) and try to start with WoW-Launcher. And I got BLZ51901016 when I try to login with any account.
Error came out with about 500ms - 1s pause after login is clicked.
![image](https://user-images.githubusercontent.com/19385791/210570930-6a2ca94a-50b6-44ca-81b9-29e2c6c32274.png)

Operating System: Microsoft Windows 10.0.19045
Backend: TrinityCore master
Is this version of client supported?

BR,
Ferdinand

**Comment by ycwjw2010** [comment]
I had a similar problem . My client version is also 47213
<img width="437" alt="屏幕截图_20230104_221530" src="https://user-images.githubusercontent.com/35825813/210574817-c3df2efd-4bbf-4704-a413-81bf1915ace1.png">
<img width="608" alt="屏幕截图_20230104_221628" src="https://user-images.githubusercontent.com/35825813/210574974-b70e1007-46d8-470f-85d0-3aacf0c4fe52.png">
<img width="819" alt="屏幕截图_20230104_221649" src="https://user-images.githubusercontent.com/35825813/210574986-c951058d-b843-4708-9f9e-8c7f3aa210fc.png">

**Comment by ycwjw2010** [comment]
> I had a similar problem . My client version is also 47213 <img alt="屏幕截图_20230104_221530" width="437" src="https://user-images.githubusercontent.com/35825813/210574817-c3df2efd-4bbf-4704-a413-81bf1915ace1.png"> <img alt="屏幕截图_20230104_221628" width="608" src="https://user-images.githubusercontent.com/35825813/210574974-b70e1007-46d8-470f-85d0-3aacf0c4fe52.png"> <img alt="屏幕截图_20230104_221649" width="819" src="https://user-images.githubusercontent.com/35825813/210574986-c951058d-b843-4708-9f9e-8c7f3aa210fc.png">

I solved the problem. 
edit bnetserver.conf : LoginREST.ExternalAddress=192.168.159.134 
192.168.159.134 is my server remote IP

**Comment by FerdinandLBS** [comment]
Problem resolved. Root cause is that the steamcommunity hooked 127.0.0.1! Dammit.
If you encountered the same issue please check if you have any proxy.
