### ISSUE TITLE
Custom files cause crash 10.0.*

### ISSUE THREAD

**Issue by KamiliaBlow** [Arctium/WoW-Launcher#32]
Any replace file in the files folder cause the client to crash when trying to load into the world.
![image](https://user-images.githubusercontent.com/25077548/227121157-f9ecfad5-6af1-4f12-8798-58824d5bb5e7.png)

**Comment by Fabi** [comment]
> Any replace file in the files folder cause the client to crash when trying to load into the world. ![image](https://user-images.githubusercontent.com/25077548/227121157-f9ecfad5-6af1-4f12-8798-58824d5bb5e7.png)

Did you try the latest source? I added some fixes a while ago but didn't update the releases yet. 
Would like to know if it works self compiled.

**Comment by KamiliaBlow** [comment]
I am using the latest version, which I built myself. Although the exact same problem was also in the old release.

**Comment by Fabi** [comment]
> I am using the latest version, which I built myself. Although the exact same problem was also in the old release.

I had someone on my discord having the same issue and saying exactly the same. When I said try again it suddenly worked 😂 
So I assumed that person didn't really use the latest source or so.

Can you upload the generated crash log (txt) and the launcher exe/dll you used?

**Comment by KamiliaBlow** [comment]
[2023-03-24 17.19.39 Crash - 7592.txt](https://github.com/Arctium/WoW-Launcher/files/11059864/2023-03-24.17.19.39.Crash.-.7592.txt)
[Arctium WoW Launcher.zip](https://github.com/Arctium/WoW-Launcher/files/11059867/Arctium.WoW.Launcher.zip)

**Comment by DintyGadget** [comment]
It looks like when I tried to compile the project into one EXE, it was going wrong. With a normal build of a project with a bunch of files, the client works

**Comment by Fabi** [comment]
> [2023-03-24 17.19.39 Crash - 7592.txt](https://github.com/Arctium/WoW-Launcher/files/11059864/2023-03-24.17.19.39.Crash.-.7592.txt) [Arctium WoW Launcher.zip](https://github.com/Arctium/WoW-Launcher/files/11059867/Arctium.WoW.Launcher.zip)

Why does sapi.dll has such a weird base address for you? that should not happen at all. Did you manually inject it or what 😂

**Comment by Fabi** [comment]
I really can't reproduce it for now but I'll push a little code change tomorrow or today.
Your crash log is really WEIRD. that one sapi.dll also has a very weird base address. That should not happen. And that big crashlog in addition to that
Bigger boobs work fine 😂 
![image](https://user-images.githubusercontent.com/246718/227660677-bb8b6b4b-3eb1-482d-8490-cbcf46e89a15.png)

**Comment by KamiliaBlow** [comment]
[files.zip](https://github.com/Arctium/WoW-Launcher/files/11067855/files.zip)
You can try the file I use.

**Comment by KamiliaBlow** [comment]
Looks like it's my addon's bug, I just tried disabling all addons and it worked. But these addons are needed, so the problem is essentially not solved :D

**Comment by KamiliaBlow** [comment]
And so the changes will be in the code? :D

**Comment by ItsMrMedic** [comment]
Getting crashes as well with certain enabled addons.
Narcissus & UnlimitedChatMessage for me

**Comment by ipro4911** [comment]
Did u try running as admin and reinstalling addons?

**Comment by KamiliaBlow** [comment]
> Did u try running as admin and reinstalling addons?

it does not help, plus reinstalling the addons does not change anything, as some addons have not been updated for a long time, but still work.

**Comment by Smerdokryl** [comment]
Just experienced this issue with the BugSack+BugGrabber addon combo.

It only happens with the "Mods" versions of the launcher, and seems to be caused specifically by the lines reading _local_ addon files. In BugGrabber's case:
```
BugSack.toc:18
  ## IconTexture: Interface\AddOns\BugSack\Media\icon

core.lua:37
  media:Register("sound", "BugSack: Fatality", "Interface\\AddOns\\"..addonName.."\\Media\\error.ogg")

ldb.lua:11
  icon = "Interface\\AddOns\\"..addonName.."\\Media\\icon"

ldb.lua:36
  plugin.icon = count == 0 and "Interface\\AddOns\\"..addonName.."\\Media\\icon" or "Interface\\AddOns\\"..addonName.."\\Media\\icon_red"
```

I'm guessing the launcher interferes somehow with the client loading these local assets into its memory storage, or perhaps with the fdid assignment?..

**Comment by Fabi** [comment]
I will fix it later but I have other stuff to do. It's caused by the file path based loading function that gets patched ny the launcher
