### ISSUE TITLE
CAS System Unable to Initialize

### ISSUE THREAD

**Issue by StonedCookieGaming** [Arctium/WoW-Launcher#33]
![Screenshot 2023-04-11 161923](https://user-images.githubusercontent.com/12970601/231290663-6ae3d788-36e8-4a27-9fed-01f7c1b92ffb.png)

I am getting this error trying to launch the client.

**Comment by Fabi** [comment]
download a full client from blizz. Or wait a bit. the configs behind those versions are bound to a git repo that isn’t updated that frequently atm
