### ISSUE TITLE
wine/proton 7.x/8.x - exception on connect

### ISSUE THREAD

**Issue by DSkywalk** [Arctium/WoW-Launcher#35]
Hello! I tryed with 1.14.0 and 1.14.2, when I try to connect a just get an exception:

![imagen](https://user-images.githubusercontent.com/560310/234405405-f8155963-194e-4850-a261-ad28a99d3c4f.png)

Tested with: wine/lutris (lutris-GE-Proton7-43-x86_x64), proton 7.0-6 and 8.0-1
HermesProxy on another computer (192.168.2.30)
__Release Signed build Nov 13, 2022__

Launch args: `--version ClassicEra --staticseed`
WTF: Portal changed to: `SET portal "192.168.2.30"`

HermesProxy CFG:
```
<add key="ClientBuild" value="40618" />
<add key="ClientSeed" value="179D3DC3235629D07113A9B3867F97A7" />
<add key="ServerBuild" value="5875" />
<add key="ExternalAddress" value="192.168.2.30" />
```

HermesProxy Log (no connect attemps)
```
22:54:06 |  Server  | Server          | Starting Hermes Proxy...
22:54:06 |  Server  | Server          | Version 2023-01-30 *official* 3.7.0
22:54:07 |  Server  | Server          | Modern (Client) Build: V1_14_0_40618
22:54:07 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
22:54:07 |  Storage | GameData        | Loading data files...
22:54:07 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
22:54:07 |  Server  | VersionChecker  | Loaded 1639 modern opcodes.
22:54:09 |  Storage | GameData        | Finished loading data.
22:54:09 |  Network | Server          | External IP: 192.168.2.30
22:54:09 |  Server  | Server          | Starting BnetTcpSession service on 0.0.0.0:1119...
22:54:09 |  Network | NetworkThread   | Network Thread Starting
22:54:09 |  Server  | Server          | Starting BnetRestApiSession service on 0.0.0.0:8081...
22:54:09 |  Network | NetworkThread   | Network Thread Starting
22:54:09 |  Server  | Server          | Starting RealmSocket service on 0.0.0.0:8084...
22:54:09 |  Network | NetworkThread   | Network Thread Starting
22:54:09 |  Server  | Server          | Starting WorldSocket service on 0.0.0.0:8086...
22:54:09 |  Network | NetworkThread   | Network Thread Starting
```

I have read in other issues that it works without problems with wine, but I can't login in.

On launcher console appear a lots of ` Waiting for client initialization...` and on close changes to `Refreshing client data...`
![imagen](https://user-images.githubusercontent.com/560310/234411245-8f310d01-cef5-4d19-b4ea-eb320511130c.png)

**Comment by infidelus** [comment]
The same error happens on retail too (not particularly surprising as it's all part of the same WoW install) even after building the launcher with the most recent updates:

![Screenshot from 2023-05-26 20-31-29](https://github.com/Arctium/WoW-Launcher/assets/39056969/c909cb07-15d8-42bb-9b28-98770f434b09)

[Edited to add]Logging into the Blizzard servers works fine so this issue only appears to affect self-hosted installs with the custom launcher.  It is not a Wine issue.

**Comment by ipro4911** [comment]
Tried running it as admin? or clearing space

**Comment by DSkywalk** [comment]
With a previous version of the Launcher (md5: 1d9bc49b180ce7dac8be9b29bc17236d - build Feb 05, 2022) is working for me.

**Comment by infidelus** [comment]
> Tried running it as admin? or clearing space

It's not a space issue as, at least on my install, there's nearly 100GB free.  Wine doesn't have, or need, a 'run as admin' option and Linux users are strongly advised not to run Wine as root.

> With a previous version of the Launcher (md5: 1d9bc49b180ce7dac8be9b29bc17236d - build Feb 05, 2022) is working for me.

Glad yours is working but I can't see how to pull a version with an md5 hash and, with no disrespect intended to the developers, the instructions for building the binary are useless (or were to me).  After downloading and installing .Net Core from the linked MS site and running the publish command all I got were errors and the project would not build.  I did eventually get it working using Visual Studio 2022 and then troubleshooting every error that occurred until I got a working binary, but the instructions definitely need improving for those that aren't developers.

**Comment by EddieHoover** [comment]
> With a previous version of the Launcher (md5: 1d9bc49b180ce7dac8be9b29bc17236d - build Feb 05, 2022) is working for me.

Are previous versions of the launcher available anywhere? I'm having the same exact issue and would like to try it.

**Comment by latchee** [comment]
Hi @DSkywalk , were you able to resolve this issue ? I am facing the same error using latest Arctium, Hermes proxy and wow 1.14.2.42597.

**Comment by latchee** [comment]
FYI I was able to make the launcher work with the Wine version lutris-ge-lol-8.7-1-x86_64

**Comment by infidelus** [comment]
Confirming the league of legends version of wine does resolve the issue for the Arctium launcher.

**Comment by Fabi** [comment]
https://github.com/Arctium/WoW-Launcher/commit/3deaa3f50b95ae918ba49ca2a4d9a895247e67f7
