### ISSUE TITLE
Asking for help: I downloaded and placed the Windows.x86_64 program in the WOW directory and modified the file Config. WTF under \_retail_\WTF to change SET portal to SET portal "192.168.0.240" However, after I started Arctium WoW Launcher, the client still cannot log in to my own server. What is the problem

### ISSUE THREAD

**Issue by kasting** [Arctium/WoW-Launcher#36]
Asking for help: I downloaded and placed the Windows.x86_64 program in the WOW directory and modified the file Config. WTF under \_retail_\WTF to change SET portal to SET portal "192.168.0.240"
However, after I started Arctium WoW Launcher, the client still cannot log in to my own server. What is the problem

**Comment by Fabi** [comment]
Not a launcher issue
