### ISSUE TITLE
Crash without internet connection

### ISSUE THREAD

**Issue by humanpride** [Arctium/WoW-Launcher#37]
I tried to run the launcher without an internet connection, but with Trinity running locally. Launch failed with an error connecting to Bliz servers.
Here is the text of the error:
```
The CAS system was unable to initialize: Tact instance creation failed. Error(7): not available
Error downloading versions data from patch service:
WOWDOWNLOAD_COULDNT_RESOLVE_HOST (http code HTTP_RESPONSE_UNDEFINED).
URL: http://ngdp.arctium.io/US/wow/49570/versions.
Error downloading CDN data from patch service:
WOWDOWNLOAD_COULDNT_RESOLVE_HOST (http code HTTP_RESPONSE_UNDEFINED).
URL: http://US.patch.battle.net:1119/wow/cdns
```
And a screenshot:
https://paste.pics/O5UYM

Is it possible to fix this error so that I can run the game without an internet connection? Maybe add "--no-update" command line option or something like that.

**Comment by ipro4911** [comment]
Same even with wifi seems the requested website is down

**Comment by Fabi** [comment]
https://github.com/Arctium/WoW-Launcher/commit/3deaa3f50b95ae918ba49ca2a4d9a895247e67f7
