### ISSUE TITLE
With the 2.5.3TBC client, the server cannot be linked,

### ISSUE THREAD

**Issue by howarduong** [Arctium/WoW-Launcher#43]
With the 2.5.3TBC client, the server cannot be linked,
I tried to link HermesProxy version 3.8 using the binary version released by Arctium2023-7-16, and the client showed that I could not link to logon.stormforge.gg Netherwing - Stormforge, I don't know where this is the problem. If you have time, you'd like to be able to handle it.

**Comment by Fabi** [comment]
?
