### ISSUE TITLE
With the 1.14.2 client, the server cannot be linked,

### ISSUE THREAD

**Issue by zhaoweizw2000** [Arctium/WoW-Launcher#45]
With the 1.14.2 client client, the server cannot be linked,
I tried to link WinterspringLauncher version 1.5, using the HermesProxy version 3.7 using the binary version released by Arctium2023-7-16, and the client showed that I could not link to logon.stormforge.gg Netherwing - Stormforge, I don't know where this is the problem. If you have time, you'd like to be able to handle it.

**Comment by zhaoweizw2000** [comment]
I get some logs:
1)low version,it can login.
Version: 2022-12-04 1.3.0
https://github.com/0blu/WinterspringLauncher

            ...      ..
       .,,,,,..        .,,
     ,,,,,    ....       ,,,
    .,,,.  ,,,,,,,,,,,    ,,,        Winterspring
    ,,,,. .,,,,   ,,,,.   ,,,,         Launcher
    .,,,,         ,,,,.   ,,,,
     ,,,,,,,...,,,,,,,   ,,,,.      Allows you to
       ,,,,,,,,,,,..   .,,,,,      play on Everlook
   ,.        .       .,,,,,,    using the modern client
     ,,,..      ..,,,,,,,.
       .,,,,,,,,,,,,,,,

BasePath: D:\game\WOW1142\WinterspringLauncher1.3
New launcher update 1.3.0 => 1.5.0
A new version was released, please update
https://github.com/0blu/WinterspringLauncher/releases
Found client in D:\game\WOW1142\game-client
Found newer version of ArctiumLauncher, upgrading from latest|Launcher Signed (2022/11/18) => latest|Launcher Signed (2023-09-06)
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at WinterspringLauncher.Launcher.ExecuteGithubDownloadIfUpdateAvailable(String description, String modulePath, GitHubReleaseInfo ghReleaseInfo, Func`2 assetSelector, Action`2 downloader) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 168
   at WinterspringLauncher.Launcher.PrepareArctiumLauncher(UpdateApiClient api, Boolean weAreOnMacOs, String arctiumPath) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 147
   at WinterspringLauncher.Launcher.<>c__DisplayClass2_0.<Main>b__5() in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 70
   at WinterspringLauncher.Launcher.IgnoreExceptions(String description, Action func) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 115
>>> Failed to prepare ArctiumLauncher, continuing anyways <<<
Starting WoW...
Starting HermesProxy...
16:24:38 |  Server  | Server          | Starting Hermes Proxy...
16:24:38 |  Server  | Server          | Version 2023-01-30 *official* 3.7.0
16:24:38 |  Server  | Server          | Modern (Client) Build: V1_14_2_42597
16:24:38 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
16:24:38 |  Storage | GameData        | Loading data files...
16:24:38 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
16:24:38 |  Server  | VersionChecker  | Loaded 1727 modern opcodes.
16:24:39 |  Storage | GameData        | Finished loading data.
16:24:39 |  Network | Server          | External IP: 127.0.0.1
16:24:39 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
16:24:39 |  Network | NetworkThread   | Network Thread Starting
16:24:39 |  Server  | Server          | Starting BnetRestApiSession service on 127.0.0.1:8081...
16:24:39 |  Network | NetworkThread   | Network Thread Starting
16:24:39 |  Server  | Server          | Starting RealmSocket service on 127.0.0.1:8084...
16:24:39 |  Network | NetworkThread   | Network Thread Starting
16:24:39 |  Server  | Server          | Starting WorldSocket service on 127.0.0.1:8086...
16:24:39 |  Network | NetworkThread   | Network Thread Starting
16:24:52 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:12998.
16:24:53 |  Network | AuthClient      | C P>S | Connecting to auth server... (realmlist addr: logon.everlook.org:3724) (resolved as: 37.59.30.120:3724)
16:24:53 |  Network | AuthClient      | Authentication succeeded!
16:24:53 |  Server  | AuthClient      | Requesting RealmList update for ZWEIVIVIAN1
16:24:53 |  Network | AuthClient      | Received 2 realms.
16:24:53 |  Server  | RealmManager    | Added realm "Everlook" at 37.59.30.120:8085
16:24:53 |  Server  | RealmManager    | Added realm "Public Test Realm" at 37.59.30.120:8087
16:24:56 |  Server  | WorldSocket     | WorldSocket:HandleAuthSession: Client 'ZWEIVIVIAN1' authenticated successfully from 127.0.0.1:13005.
16:24:56 |  Network | WorldClient     | Connecting to world server...
16:24:56 |  Network | WorldClient     | Connection established!
16:24:56 |  Network | WorldClient     | Authentication succeeded!
16:24:56 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14053) (Got unknown packet from ModernClient)
16:24:56 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14019) (Got unknown packet from ModernClient)
16:24:56 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14018) (Got unknown packet from ModernClient)
16:24:56 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14073) (Got unknown packet from ModernClient)
16:24:56 |  Error   | AuthClient      | C P<S | Socket Closed By Server
16:24:56 |  Warning | BnetServices    | [WorldSocket][127.0.0.1:13005, Account: ZWEIVIVIAN1, Game account: ZWEIVIVIAN1] Client requested service ResourcesService/m:1 but this service is not implemented?
16:24:59 |  Server  | WorldSocket     | Client disconnected with reason 13.
16:24:59 |  Error   | WorldClient     | C P<S | Socket Closed By GameWorldServer (header)

2)high version,it can't login, have lettle logs.
Version: 2023-08-12 1.5.0
https://github.com/0blu/WinterspringLauncher

            ...      ..
       .,,,,,..        .,,
     ,,,,,    ....       ,,,
    .,,,.  ,,,,,,,,,,,    ,,,        Winterspring
    ,,,,. .,,,,   ,,,,.   ,,,,         Launcher
    .,,,,         ,,,,.   ,,,,
     ,,,,,,,...,,,,,,,   ,,,,.      Allows you to
       ,,,,,,,,,,,..   .,,,,,      play on Everlook
   ,.        .       .,,,,,,    using the modern client
     ,,,..      ..,,,,,,,.
       .,,,,,,,,,,,,,,,

BasePath: D:\game\WOW1142\WinterspringLauncher1.5
Found client in D:\game\WOW1142\game-client
Starting WoW...
Starting HermesProxy...
16:26:33 |  Server  | Server          | Starting Hermes Proxy...
16:26:33 |  Server  | Server          | Version 2023-01-30 *official* 3.7.0
16:26:34 |  Server  | Server          | Modern (Client) Build: V1_14_0_40618
16:26:34 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
16:26:34 |  Storage | GameData        | Loading data files...
16:26:34 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
16:26:34 |  Server  | VersionChecker  | Loaded 1639 modern opcodes.
16:26:35 |  Storage | GameData        | Finished loading data.
16:26:35 |  Network | Server          | External IP: 127.0.0.1
16:26:35 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
16:26:35 |  Network | NetworkThread   | Network Thread Starting
16:26:35 |  Server  | Server          | Starting BnetRestApiSession service on 127.0.0.1:8081...
16:26:35 |  Network | NetworkThread   | Network Thread Starting
16:26:35 |  Server  | Server          | Starting RealmSocket service on 127.0.0.1:8084...
16:26:35 |  Network | NetworkThread   | Network Thread Starting
16:26:35 |  Server  | Server          | Starting WorldSocket service on 127.0.0.1:8086...
16:26:35 |  Network | NetworkThread   | Network Thread Starting
16:26:49 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:13061.
-------------
World of Warcraft was closed
You can close this window
-------------

**Comment by zbluekuma** [comment]
+1

**Comment by xhyanhao9** [comment]
wait anxiously

**Comment by Fabi** [comment]
Not Do not report issues to random other 'launchers' or so. It's not related to this launcher.
