### ISSUE TITLE
Question about 2.5.3 connection 2.4.3cmangos

### ISSUE THREAD

**Issue by howarduong** [Arctium/WoW-Launcher#46]
About the tutorial section, this description
“Static Auth Seed Usage
Use the --staticseed launch parameter
On server side add 179D3DC3235629D07113A9B3867F97A7 as auth seed in the database.”

I use the 2.4.3cmangos server and cannot find the database field that matches it, what should I do?

I was wondering if I am now playing 2.4.3 games with a 2.5.3 client.
Is it using Plan A? Client > ArctiumWoW-Launcher-->HermesProxy-->cmangos.

Or Plan B? Client->ArctiumWoW-Launcher-->cmangos modifies the database static seed as described above.

**Comment by Fabi** [comment]
Ask at hermesproxy
