### ISSUE TITLE
Whether we can build a UI interface to make it more convenient.

### ISSUE THREAD

**Issue by howarduong** [Arctium/WoW-Launcher#9]
This is a great project. I have successfully built a 1.14 WOW game by using it combined with hermesproxy. Whether we can build a UI interface to make it more convenient.

**Comment by Fabi** [comment]
> This is a great project. I have successfully built a 1.14 WOW game by using it combined with hermesproxy. Whether we can build a UI interface to make it more convenient.

What would you like to see in such a version? Game folder you can set (and save it)? Server address settings? ...?

**Comment by howarduong** [comment]
Thank you so much for listening to my advice, it was how I felt after a week or so of using it. If you can accept and correct these, it will be beneficial to the lander's progress. 1, the first time I configured, it took a lot of time, the login needs to be added after the shortcut - version ClassicEra I tried many times, but did not succeed, and finally I checked some basic settings information, only to know that there is a space missing from the address and it. Let me waste a lot of time with people like me who don't understand, and it would be great if you could make a simpler UI interface with a direct link to the game. 2, the login file package has a lot of file content, about 200 more, I don't know if these are necessary files, whether they can be classified into a separate folder, so that the wow file sorting is more concise. These are just my personal suggestions, I'm playing the 1.14classic version.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Fabian K?nig ***@***.***>
发送时间: Thursday, May 26, 2022 5:25:12 PM
收件人: Arctium/WoW-Launcher ***@***.***>
抄送: howarduong ***@***.***>; Author ***@***.***>
主题: Re: [Arctium/WoW-Launcher] Whether we can build a UI interface to make it more convenient. (Issue #9)


This is a great project. I have successfully built a 1.14 WOW game by using it combined with hermesproxy. Whether we can build a UI interface to make it more convenient.

What would you like to see in such a version? Game folder you can set (and save it)? Server address settings? ...?

―

**Comment by Fabi** [comment]
> Thank you so much for listening to my advice, it was how I felt after a week or so of using it. If you can accept and correct these, it will be beneficial to the lander's progress. 1, the first time I configured, it took a lot of time, the login needs to be added after the shortcut - version ClassicEra I tried many times, but did not succeed, and finally I checked some basic settings information, only to know that there is a space missing from the address and it. Let me waste a lot of time with people like me who don't understand, and it would be great if you could make a simpler UI interface with a direct link to the game. 2, the login file package has a lot of file content, about 200 more, I don't know if these are necessary files, whether they can be classified into a separate folder, so that the wow file sorting is more concise. These are just my personal suggestions, I'm playing the 1.14classic version. 从 Windows 版邮件<[https://go.microsoft.com/fwlink/?LinkId=550986>发送](https://go.microsoft.com/fwlink/?LinkId=550986>%E5%8F%91%E9%80%81)
> […](#)

I'll see what I can do. From our side that would be a Win10+ supported app only though.
About the high amount of files (I guess you mean the ones after building this launcher) you just have to follow the native build instructions in the readme. It's a single file exe then.

**Comment by howarduong** [comment]
Thank you for listening to my advice

**Comment by Fabi** [comment]
https://github.com/Arctium/WoW-Launcher/commit/3deaa3f50b95ae918ba49ca2a4d9a895247e67f7
